language: node_js

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "Clooooode"
  - git config user.email "jackey8616@gmail.com"
  - git add .
  - git commit -m "Travis Build Bot Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master

